import { prisma } from '@/lib/prisma'
import { format } from 'date-fns'
import { recalcInvoiceStatus } from '@/lib/invoice-status'

export async function POST(request: Request) {
  const authHeader = request.headers.get('Authorization')
  const expectedToken = process.env.CRON_SECRET
  if (expectedToken && authHeader !== `Bearer ${expectedToken}`) {
    return new Response('Unauthorized', { status: 401 })
  }

  try {
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    const dayOfMonth = today.getDate()
    const lastDayOfMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate()

    // Find active leases where today matches the payment due day
    const leases = await prisma.lease.findMany({
      where: {
        status: { in: ['ACTIVE', 'MONTH_TO_MONTH'] },
        startDate: { lte: today },
        endDate: { gte: today },
        OR: [
          { paymentDueDay: dayOfMonth },
          // For leases with paymentDueDay > last day of month, trigger on last day
          ...(dayOfMonth === lastDayOfMonth
            ? [{ paymentDueDay: { gt: lastDayOfMonth } }]
            : []),
        ],
      },
      include: {
        tenant: true,
        unit: {
          include: {
            propertyProfile: {
              include: { workspace: true },
            },
          },
        },
      },
    })

    let generated = 0
    let skipped = 0
    let failed = 0

    const monthLabel = format(today, 'MMMM yyyy')
    const period = format(today, 'yyyy-MM')

    for (const lease of leases) {
      try {
        // Dedup: check if an invoice already exists for this lease+period with a RENT line
        const existingInvoice = await prisma.invoice.findFirst({
          where: {
            leaseId: lease.id,
            period,
            lineItems: { some: { chargeType: 'RENT' } },
          },
        })
        if (existingInvoice) { skipped++; continue }

        const invoiceNumber = `RENT-${Date.now().toString(36).toUpperCase()}`
        const autoSend = lease.unit.propertyProfile.autoGenerateRentInvoice

        const lineItems: Array<{ description: string; quantity: number; unitPrice: number; chargeType: string }> = [
          {
            description: `Rent — ${monthLabel}`,
            quantity: 1,
            unitPrice: Number(lease.monthlyRent),
            chargeType: 'RENT',
          },
        ]

        // Include recurring additional charges from lease addenda
        const addlCharges = lease.additionalCharges as Array<{ label: string; amount: number; frequency: string }> | null
        if (addlCharges) {
          for (const ac of addlCharges) {
            if (ac.frequency === 'monthly') {
              lineItems.push({
                description: `${ac.label} — ${monthLabel}`,
                quantity: 1,
                unitPrice: ac.amount,
                chargeType: 'OTHER',
              })
            }
          }
        }

        await prisma.invoice.create({
          data: {
            leaseId: lease.id,
            tenantId: lease.tenantId,
            invoiceNumber,
            status: autoSend ? 'SENT' : 'DRAFT',
            issueDate: today,
            dueDate: today,
            currency: lease.currency ?? 'USD',
            period,
            autoGenerated: true,
            notes: `Monthly rent — ${monthLabel}`,
            sentAt: autoSend ? today : null,
            sentTo: autoSend ? lease.tenant.email : null,
            lineItems: {
              create: lineItems.map(li => ({
                description: li.description,
                quantity: li.quantity,
                unitPrice: li.unitPrice,
                isTaxLine: false,
                chargeType: li.chargeType,
              })),
            },
          },
        })

        generated++
      } catch (err) {
        console.error('[rent/generate] failed for lease', lease.id, err)
        failed++
      }
    }

    // Late fee assessment: find overdue invoices with RENT line items
    const graceBuffer = 5 // max grace days to check
    const overdueInvoices = await prisma.invoice.findMany({
      where: {
        status: { in: ['SENT', 'PARTIAL', 'OVERDUE'] },
        lineItems: { some: { chargeType: 'RENT' } },
        dueDate: { lt: new Date(today.getTime() - graceBuffer * 86400000) },
        lease: {
          lateFeeAmount: { not: null },
          status: { in: ['ACTIVE', 'MONTH_TO_MONTH'] },
        },
      },
      include: {
        lease: { select: { lateFeeAmount: true, lateFeeGraceDays: true } },
        lineItems: { where: { chargeType: 'LATE_FEE' } },
      },
    })

    for (const inv of overdueInvoices) {
      const graceDays = inv.lease?.lateFeeGraceDays ?? 5
      const cutoff = new Date(inv.dueDate.getTime() + graceDays * 86400000)
      if (today <= cutoff) continue

      // Check if late fee already exists on this invoice
      if (inv.lineItems.length > 0) continue

      await prisma.invoiceLineItem.create({
        data: {
          invoiceId: inv.id,
          description: `Late fee — ${format(inv.dueDate, 'MMMM yyyy')}`,
          quantity: 1,
          unitPrice: inv.lease!.lateFeeAmount!,
          isTaxLine: false,
          chargeType: 'LATE_FEE',
        },
      })

      await recalcInvoiceStatus(inv.id)
    }

    return Response.json({ generated, skipped, failed })
  } catch (err) {
    console.error('[rent/generate] error:', err)
    return new Response('Internal error', { status: 500 })
  }
}
