/**
 * Invoice-first migration: migrate TenantCharge + TenantPayment → Invoice / InvoiceLineItem / InvoicePayment
 *
 * Run with:
 *   DATABASE_URL="$(netlify env:get DATABASE_URL)" npx tsx prisma/migrations/invoice-first/migrate.ts
 *
 * This script is idempotent — safe to re-run.
 */

import { PrismaClient } from '../../src/generated/prisma/client'
import { randomUUID } from 'crypto'

function createId() { return randomUUID().replace(/-/g, '').slice(0, 20) }

const prisma = new PrismaClient()

function yyyyMM(date: Date): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
}

async function main() {
  console.log('[migrate] Starting invoice-first migration...')

  // We use raw queries to read TenantCharge and TenantPayment since they're
  // no longer in the Prisma schema. Raw SQL reads from the existing tables
  // before db:push drops them.

  // ── Step A: Migrate orphan charges (no invoiceLineItemId) ──────────────────

  const orphanCharges: Array<{
    id: string
    leaseId: string
    tenantId: string
    type: string
    description: string | null
    amount: string
    dueDate: Date
    forgivenAt: Date | null
    forgivenBy: string | null
    forgivenReason: string | null
    maintenanceRequestId: string | null
    createdAt: Date
  }> = await prisma.$queryRaw`
    SELECT id, "leaseId", "tenantId", type, description, amount, "dueDate",
           "forgivenAt", "forgivenBy", "forgivenReason", "maintenanceRequestId", "createdAt"
    FROM "TenantCharge"
    WHERE "invoiceLineItemId" IS NULL
    ORDER BY "dueDate" ASC
  `

  console.log(`[migrate] Found ${orphanCharges.length} orphan charges`)

  // Group by (tenantId, leaseId, YYYY-MM)
  const groups = new Map<string, typeof orphanCharges>()
  for (const charge of orphanCharges) {
    const key = `${charge.tenantId}|${charge.leaseId}|${yyyyMM(charge.dueDate)}`
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key)!.push(charge)
  }

  const createdInvoiceIds: string[] = []

  for (const [key, charges] of groups) {
    const [tenantId, leaseId, period] = key.split('|')
    const earliestDue = charges.reduce((min, c) => (c.dueDate < min ? c.dueDate : min), charges[0].dueDate)

    // Check if we already created a migration invoice for this group (idempotency)
    const existing = await prisma.invoice.findFirst({
      where: { leaseId, tenantId, period, notes: 'Migrated from legacy charges' },
    })
    if (existing) {
      console.log(`[migrate] Skipping group ${key} — migration invoice already exists`)
      createdInvoiceIds.push(existing.id)
      continue
    }

    // Get lease currency
    const lease = await prisma.lease.findUnique({ where: { id: leaseId }, select: { currency: true } })
    const currency = lease?.currency ?? 'USD'

    const invoiceNumber = `MIG-${createId()}`

    const invoice = await prisma.invoice.create({
      data: {
        leaseId,
        tenantId,
        invoiceNumber,
        period,
        autoGenerated: true,
        issueDate: earliestDue,
        dueDate: earliestDue,
        currency,
        status: 'DRAFT', // computed in Step C
        notes: 'Migrated from legacy charges',
        lineItems: {
          create: charges.map(c => ({
            description: c.description ?? `${c.type} charge`,
            quantity: 1,
            unitPrice: Number(c.amount),
            isTaxLine: false,
            chargeType: c.type,
            forgivenAt: c.forgivenAt,
            forgivenBy: c.forgivenBy,
            forgivenReason: c.forgivenReason,
            maintenanceRequestId: c.maintenanceRequestId,
            createdAt: c.createdAt,
          })),
        },
      },
    })

    createdInvoiceIds.push(invoice.id)
  }

  console.log(`[migrate] Created ${createdInvoiceIds.length} migration invoices from orphan charges`)

  // ── Step B: Migrate orphan payments ────────────────────────────────────────

  const orphanPayments: Array<{
    id: string
    leaseId: string | null
    tenantId: string
    amount: string
    paidDate: Date
    transactionId: string | null
    paymentMethod: string | null
    notes: string | null
    sourceDeleted: boolean
    voidedAt: Date | null
    voidedBy: string | null
    voidReason: string | null
    createdAt: Date
  }> = await prisma.$queryRaw`
    SELECT id, "leaseId", "tenantId", amount, "paidDate", "transactionId",
           "paymentMethod", notes, "sourceDeleted", "voidedAt", "voidedBy", "voidReason", "createdAt"
    FROM "TenantPayment"
    ORDER BY "paidDate" ASC
  `

  console.log(`[migrate] Found ${orphanPayments.length} payments to migrate`)

  for (const payment of orphanPayments) {
    // Idempotency: check by transactionId (unique) or createdAt+amount+tenantId as fallback
    if (payment.transactionId) {
      const existing = await prisma.invoicePayment.findUnique({
        where: { transactionId: payment.transactionId },
      })
      if (existing) {
        console.log(`[migrate] Skipping payment ${payment.id} — already migrated (transactionId conflict)`)
        continue
      }
    }

    const paymentPeriod = yyyyMM(payment.paidDate)
    let targetInvoice: { id: string } | null = null

    if (payment.leaseId) {
      // Try 1: matching period + same lease
      targetInvoice = await prisma.invoice.findFirst({
        where: { leaseId: payment.leaseId, period: paymentPeriod },
        select: { id: true },
        orderBy: { dueDate: 'asc' },
      })

      // Try 2: oldest open invoice for this lease
      if (!targetInvoice) {
        targetInvoice = await prisma.invoice.findFirst({
          where: {
            leaseId: payment.leaseId,
            status: { in: ['SENT', 'PARTIAL', 'OVERDUE'] },
          },
          select: { id: true },
          orderBy: { dueDate: 'asc' },
        })
      }

      // Try 3: any invoice for this lease
      if (!targetInvoice) {
        targetInvoice = await prisma.invoice.findFirst({
          where: { leaseId: payment.leaseId },
          select: { id: true },
          orderBy: { dueDate: 'desc' },
        })
      }
    }

    // Try by tenantId if lease-based search failed
    if (!targetInvoice) {
      targetInvoice = await prisma.invoice.findFirst({
        where: { tenantId: payment.tenantId },
        select: { id: true },
        orderBy: { dueDate: 'desc' },
      })
    }

    // Last resort: create a catch-all invoice
    if (!targetInvoice) {
      const catchAllInvoice = await prisma.invoice.findFirst({
        where: { tenantId: payment.tenantId, period: paymentPeriod, notes: 'Migrated catch-all invoice' },
        select: { id: true },
      })
      if (catchAllInvoice) {
        targetInvoice = catchAllInvoice
      } else {
        const newInvoice = await prisma.invoice.create({
          data: {
            tenantId: payment.tenantId,
            leaseId: payment.leaseId,
            invoiceNumber: `MIG-${createId()}`,
            period: paymentPeriod,
            autoGenerated: true,
            issueDate: payment.paidDate,
            dueDate: payment.paidDate,
            currency: 'USD',
            status: 'PAID',
            notes: 'Migrated catch-all invoice',
            lineItems: {
              create: [{
                description: 'Migrated payment (no matching charge)',
                quantity: 1,
                unitPrice: Number(payment.amount),
                isTaxLine: false,
                chargeType: 'OTHER',
              }],
            },
          },
        })
        targetInvoice = { id: newInvoice.id }
      }
    }

    // Check transactionId conflict
    let txId: string | null = payment.transactionId
    let notes = payment.notes ?? 'Migrated from legacy payment'
    if (txId) {
      const conflict = await prisma.invoicePayment.findUnique({ where: { transactionId: txId } })
      if (conflict) {
        txId = null
        notes += ' (bank transaction link lost — was already claimed by invoice payment)'
      }
    }

    await prisma.invoicePayment.create({
      data: {
        invoiceId: targetInvoice.id,
        amount: Number(payment.amount),
        paidDate: payment.paidDate,
        paymentMethod: payment.paymentMethod,
        notes,
        ...(txId ? { transactionId: txId } : {}),
        voidedAt: payment.voidedAt,
        voidedBy: payment.voidedBy,
        voidReason: payment.voidReason,
        sourceDeleted: payment.sourceDeleted,
        createdAt: payment.createdAt,
      },
    })
  }

  console.log(`[migrate] Migrated ${orphanPayments.length} payments`)

  // ── Step C: Compute migrated invoice statuses ───────────────────────────────

  const now = new Date()
  for (const invoiceId of createdInvoiceIds) {
    const invoice = await prisma.invoice.findUnique({
      where: { id: invoiceId },
      include: { lineItems: true, payments: true },
    })
    if (!invoice) continue

    const lineItemTotal = invoice.lineItems
      .filter(li => !li.forgivenAt)
      .reduce((s, li) => s + Number(li.quantity) * Number(li.unitPrice), 0)
    const paymentTotal = invoice.payments
      .filter(p => !p.voidedAt)
      .reduce((s, p) => s + Number(p.amount), 0)

    let newStatus: string
    if (lineItemTotal === 0) newStatus = 'VOID'
    else if (paymentTotal >= lineItemTotal) newStatus = 'PAID'
    else if (paymentTotal > 0) newStatus = 'PARTIAL'
    else if (invoice.dueDate < now) newStatus = 'OVERDUE'
    else newStatus = 'SENT'

    await prisma.invoice.update({ where: { id: invoiceId }, data: { status: newStatus } })
  }

  console.log(`[migrate] Recomputed statuses for ${createdInvoiceIds.length} migration invoices`)

  // ── Step D: Handle already-linked charges ──────────────────────────────────

  const linkedCharges: Array<{
    id: string
    invoiceLineItemId: string
    forgivenAt: Date | null
    forgivenBy: string | null
    forgivenReason: string | null
    maintenanceRequestId: string | null
  }> = await prisma.$queryRaw`
    SELECT id, "invoiceLineItemId", "forgivenAt", "forgivenBy", "forgivenReason", "maintenanceRequestId"
    FROM "TenantCharge"
    WHERE "invoiceLineItemId" IS NOT NULL
  `

  console.log(`[migrate] Copying forgiveness data from ${linkedCharges.length} linked charges`)

  for (const charge of linkedCharges) {
    await prisma.invoiceLineItem.update({
      where: { id: charge.invoiceLineItemId },
      data: {
        forgivenAt: charge.forgivenAt,
        forgivenBy: charge.forgivenBy,
        forgivenReason: charge.forgivenReason,
        maintenanceRequestId: charge.maintenanceRequestId,
      },
    })
  }

  console.log('[migrate] Migration complete.')
}

main()
  .catch(err => {
    console.error('[migrate] Error:', err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
