import { auth } from '@clerk/nextjs/server'
import { prisma } from '@/lib/prisma'
import { ok, unauthorized, notFound, serverError } from '@/lib/api-response'

interface RouteParams { params: Promise<{ id: string; unitId: string }> }

export async function GET(_request: Request, { params }: RouteParams) {
  try {
    const { userId } = await auth()
    if (!userId) return unauthorized()
    const { id, unitId } = await params

    const project = await prisma.workspace.findFirst({
      where: { id, userId, type: 'PROPERTY' },
      include: { propertyProfile: { select: { units: { where: { id: unitId }, select: { id: true } } } } },
    })
    if (!project?.propertyProfile?.units[0]) return notFound('Unit not found')

    const lease = await prisma.lease.findFirst({
      where: { unitId, status: { in: ['ACTIVE', 'EXPIRING_SOON', 'MONTH_TO_MONTH'] } },
      include: { tenant: { select: { id: true, name: true, email: true, phone: true } } },
      orderBy: { startDate: 'desc' },
    })
    if (!lease) return ok({ lease: null, invoices: [], suggestions: [], totalCharged: 0, totalPaid: 0, balance: 0 })

    const [invoices, suggestions] = await Promise.all([
      prisma.invoice.findMany({
        where: { leaseId: lease.id, status: { not: 'VOID' } },
        include: {
          lineItems: true,
          payments: true,
        },
        orderBy: { dueDate: 'desc' },
      }),
      prisma.invoicePaymentSuggestion.findMany({
        where: {
          invoice: { leaseId: lease.id },
          status: 'PENDING',
        },
        include: {
          transaction: { select: { id: true, description: true, date: true, amount: true } },
          invoice: { select: { id: true, invoiceNumber: true } },
        },
        orderBy: { createdAt: 'desc' },
      }),
    ])

    let totalCharged = 0
    let totalPaid = 0

    const mappedInvoices = invoices.map(inv => {
      const lineItemTotal = inv.lineItems
        .filter(li => !li.forgivenAt && !li.isTaxLine)
        .reduce((s, li) => s + Number(li.quantity) * Number(li.unitPrice), 0)
      const paymentTotal = inv.payments
        .filter(p => !p.voidedAt)
        .reduce((s, p) => s + Number(p.amount), 0)
      const outstanding = lineItemTotal - paymentTotal

      totalCharged += lineItemTotal
      totalPaid += paymentTotal

      return {
        id: inv.id,
        invoiceNumber: inv.invoiceNumber,
        status: inv.status,
        period: inv.period,
        autoGenerated: inv.autoGenerated,
        issueDate: inv.issueDate.toISOString(),
        dueDate: inv.dueDate.toISOString(),
        lineItems: inv.lineItems.map(li => ({
          id: li.id,
          description: li.description,
          quantity: Number(li.quantity),
          unitPrice: Number(li.unitPrice),
          chargeType: li.chargeType,
          isTaxLine: li.isTaxLine,
          forgivenAt: li.forgivenAt?.toISOString() ?? null,
          forgivenReason: li.forgivenReason,
          maintenanceRequestId: li.maintenanceRequestId,
          createdAt: li.createdAt.toISOString(),
        })),
        payments: inv.payments.map(p => ({
          id: p.id,
          amount: Number(p.amount),
          paidDate: p.paidDate.toISOString(),
          paymentMethod: p.paymentMethod,
          notes: p.notes,
          voidedAt: p.voidedAt?.toISOString() ?? null,
          voidReason: p.voidReason ?? null,
          transactionId: p.transactionId,
          sourceDeleted: p.sourceDeleted,
          createdAt: p.createdAt.toISOString(),
        })),
        lineItemTotal,
        paymentTotal,
        outstanding,
      }
    })

    return ok({
      lease: {
        id: lease.id,
        status: lease.status,
        startDate: lease.startDate.toISOString(),
        endDate: lease.endDate.toISOString(),
        monthlyRent: Number(lease.monthlyRent),
        paymentDueDay: lease.paymentDueDay,
        lateFeeAmount: lease.lateFeeAmount ? Number(lease.lateFeeAmount) : null,
        lateFeeGraceDays: lease.lateFeeGraceDays,
        tenant: lease.tenant,
      },
      invoices: mappedInvoices,
      suggestions: suggestions.map(s => ({
        id: s.id,
        confidence: s.confidence,
        reasoning: s.reasoning,
        invoiceId: s.invoice.id,
        invoiceNumber: s.invoice.invoiceNumber,
        transaction: {
          id: s.transaction.id,
          description: s.transaction.description,
          date: s.transaction.date.toISOString(),
          amount: Number(s.transaction.amount),
        },
        createdAt: s.createdAt.toISOString(),
      })),
      totalCharged,
      totalPaid,
      balance: totalCharged - totalPaid,
    })
  } catch {
    return serverError('Failed to fetch ledger')
  }
}
